#!/bin/bash
while ! nc -z ${proxy_address} 3128; do sleep 0.1; done 
echo "Acquire::http::Proxy \"http://${proxy_address}:3128\";" > /etc/apt/apt.conf.d/02proxy
echo "proxy = ${proxy_address}:3128" > ~/.curlrc
echo "noproxy = 127.0.0.1,localhost,169.254.169.254" >> ~/.curlrc
curl https://releases.rancher.com/install-docker/${docker_version_agent}.sh | sh
echo '{"insecure-registries": ["${prefix}-registry.${domain}:5000"]}' > /etc/docker/daemon.json
service docker restart
until docker inspect ${prefix}-registry.${domain}:5000/rancher/rancher-agent:${rancher_version} > /dev/null 2>&1; do
  docker pull ${prefix}-registry.${domain}:5000/rancher/rancher-agent:${rancher_version}
  sleep 2
done
